
version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URI=mongodb+srv://1garodev:admin@shortlinkcluster0.hhfk0kc.mongodb.net/?retryWrites=true&w=majority&appName=ShortLinkCluster0
      - DATABASE=shortlink
      - COLLECTION=tinyurl
    ports:
      - "3001:3000"

  api02:
    <<: *api
    hostname: api02
    environment:
      - MONGODB_URI=mongodb+srv://1garodev:admin@shortlinkcluster0.hhfk0kc.mongodb.net/?retryWrites=true&w=majority&appName=ShortLinkCluster0
      - DATABASE=shortlink
      - COLLECTION=tinyurl
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"

networks:
  default:
    driver: bridge
    name: shortlink